### ISSUE TITLE
Inline::Perl5 does not install on Perl6 2019.03.1-585-gb8669fe6f

### ISSUE THREAD

**Issue by Xliff** [niner/Inline-Perl6#4]
When installing via zef, I get the following error:

```
New type P6Bar for Foo is not a mixin type
  in method new at /home/cbwood/.zef/store/Inline-Perl5-0.38.tar.gz/Inline-Perl5-0.38/lib/Inline/Perl5/ClassHOW.pm6 (Inline::Perl5::ClassHOW) line 47
  in block <unit> at t/inherit.t line 28
```

This prevents the install. Is it safe to --force it?

**Comment by niner** [comment]
I've just uploaded Inline::Perl5 version 0.39 which fixes the issue. May take a while to show up in zef though with the ongoing infrastructure issues...
